# Generated by Django 6.0 on 2026-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatthread",
            options={"ordering": ["-is_pinned", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="chatthread",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
